Milestone 8: Models
AbigiyaTY/Portofolio- pull request #10
Opened 2022-07-19 11:34 UTC by AbigiyaTY

##  Responsive hamburger-menu

In this milestone I:

- Made hamburger menu responsive and connected nav item to their link in index.html
- Add styling to the responsive hamburger menu using CSS
- Add event listener to the hamburger menu using Javascript

2022-07-19 11:38 UTC, vechicin reviewed
# Hi @AbigiyaTY ✋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😞 

## Invalid Code Review Request ⚠️ 

You have submitted a project, that is missing the ESlint linters. Please install them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-19 12:31 UTC, zieeco requested changes
Hi @AbigiyaTY ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions

- Kindly adjust the styling in your header so that your hamburger is well aligned to the left end.
- Kindly ensure the first section of your portfolio is well aligned in the center to improve your design.

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 12:31 UTC, zieeco commented on css/style.css
> +}
- Please, kindly ensure your mobile menu and contents match the Figma design as much as you can below:

*your design*
![n](https://user-images.githubusercontent.com/59397159/179748243-b17137b8-c4fc-4fc1-8cad-567f6d829329.png)
* figma design*
![match](https://user-images.githubusercontent.com/59397159/179748247-d82bcea9-ef7d-41a1-9c46-3b73d311da41.png)

2022-07-19 12:31 UTC, zieeco commented on css/style.css
> +}
*README FILE*

> Please, kindly update your readme by doing the following to make your readme more professional.
- Add a "Getting started" header and add some instructions on how users can have your project up and running locally on their machine
- Add the "Acknowledgement" header and ad its content giving appropriate credit to Figma, for using their design template.
- Update the MIT.md file and add the licensed content as of now, the link is broken.
- Update the description of your portfolio to be more descriptive as what you have now doesn't say anything about your portfolio.

2022-07-20 06:21 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @AbigiyaTY,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-20 06:50 UTC, merged