Milestone 2: Models
AbigiyaTY/Portofolio- pull request #2
Opened 2022-07-01 19:20 UTC by AbigiyaTY

**Building Portfolio page milestone 2: Models**

In this milestone I:

- Build the work display section
- Build the contact us section
- Added styling to both section

2022-07-01 21:16 UTC, isaacpitwa requested changes
Hi @AbigiyaTY  🙂 ,

You have done a tremendous job setting up your project. I really like it :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)


## Highlights 
- All linters are passing  ✅
- Correct use of GitHub flow ✅
- Well documented Repository ✅
-  Clean and readable code base ✅

## Required changes ♻️ 

Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @isaacpitwa.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 21:16 UTC, isaacpitwa commented on css/style.css
>  @media (min-width: 375px) {
Great work implementing the desktop version 👏🏽
However, your design is not visible on most mobile devices i.e devices width > 375px.

- [ ] Kindly consider expanding the range of mobile devices to cater to mobile devices  as the  maximum mobile screen size is  480px . Check the screenshots below.
<img width="453" alt="Screenshot 2022-07-02 at 00 11 54" src="https://user-images.githubusercontent.com/31113416/176969225-99084dcd-074a-460a-bb27-c15b57791ba3.png">
<img width="579" alt="Screenshot 2022-07-02 at 00 11 43" src="https://user-images.githubusercontent.com/31113416/176969282-a376f711-fa27-40e2-9fe5-a1ff9c414ec8.png">

2022-07-01 21:16 UTC, isaacpitwa commented on index.html
> +            <h1 class="work-title">MY RECENT WORK</h1>
- [ ] Kindly consider having a single h1 in a webpage. h1 is used to indicate the most important heading (for this case, your name), having more than one may lead to spamming. kindly change this to one of the least important headings.

2022-07-02 00:44 UTC, danielufeli approved these changes
Hi @AbigiyaTY ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 01:04 UTC, merged